### ISSUE TITLE
want as early as possible solution....see n suggest the solution

### ISSUE THREAD

**Issue by AnjumMomin** [AnjumMomin/rano#2]
shrikant@YM-SAJJANGAD:~/workspace/anjumTests/selenium$ protractor searchUCon.js
(node:10462) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[13:52:15] I/launcher - Running 1 instances of WebDriver
[13:52:15] I/hosted - Using the selenium server at  http://localhost:4444/wd/hub
[13:52:15] E/launcher - Error code: 135
[13:52:15] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[13:52:15] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:623:16)
    at Hosted.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[13:52:15] E/launcher - Process exited with error code 135

**Comment by AnjumMomin** [comment]
conf file:-
 exports.config={ seleniumAddress:' http://localhost:4444/wd/hub',
     capabilities: { 'browserName': 'chrome', 
	                  chromeOnly:true , directConnect: true
	                 }  ,
specs:['searchU.js']
};
